
---
events:
  -
    kind: "find-v1"
    backtrace:
      - "/opt/homebrew/share/cmake/Modules/CMakeDetermineSystem.cmake:12 (find_program)"
      - "CMakeLists.txt:9 (project)"
    mode: "program"
    variable: "CMAKE_UNAME"
    description: "Path to a program."
    settings:
      SearchFramework: "FIRST"
      SearchAppBundle: "FIRST"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "uname"
    candidate_directories:
      - "/Users/yadnyesh8250/.gemini/antigravity-ide/bin/"
      - "/Users/yadnyesh8250/.antigravity-ide/antigravity-ide/bin/"
      - "/Users/yadnyesh8250/.antigravity/antigravity/bin/"
      - "/usr/local/bin/"
      - "/System/Cryptexes/App/usr/bin/"
      - "/usr/bin/"
      - "/bin/"
      - "/usr/sbin/"
      - "/sbin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin/"
      - "/pkg/env/global/bin/"
      - "/opt/homebrew/bin/"
    searched_directories:
      - "/Users/yadnyesh8250/.gemini/antigravity-ide/bin/uname"
      - "/Users/yadnyesh8250/.antigravity-ide/antigravity-ide/bin/uname"
      - "/Users/yadnyesh8250/.antigravity/antigravity/bin/uname"
      - "/usr/local/bin/uname"
      - "/System/Cryptexes/App/usr/bin/uname"
    found: "/usr/bin/uname"
    search_context:
      ENV{PATH}:
        - "/Users/yadnyesh8250/.gemini/antigravity-ide/bin"
        - "/Users/yadnyesh8250/.antigravity-ide/antigravity-ide/bin"
        - "/Users/yadnyesh8250/.antigravity-ide/antigravity-ide/bin"
        - "/Users/yadnyesh8250/.antigravity/antigravity/bin"
        - "/Users/yadnyesh8250/.antigravity/antigravity/bin"
        - "/Users/yadnyesh8250/.antigravity/antigravity/bin"
        - "/Users/yadnyesh8250/.antigravity/antigravity/bin"
        - "/Users/yadnyesh8250/.antigravity/antigravity/bin"
        - "/usr/local/bin"
        - "/System/Cryptexes/App/usr/bin"
        - "/usr/bin"
        - "/bin"
        - "/usr/sbin"
        - "/sbin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin"
        - "/pkg/env/global/bin"
        - "/opt/homebrew/bin"
  -
    kind: "message-v1"
    backtrace:
      - "/opt/homebrew/share/cmake/Modules/CMakeDetermineSystem.cmake:218 (message)"
      - "CMakeLists.txt:9 (project)"
    message: |
      The system is: Darwin - 25.6.0 - arm64
  -
    kind: "find-v1"
    backtrace:
      - "/opt/homebrew/share/cmake/Modules/CMakeDetermineCompiler.cmake:54 (find_program)"
      - "/opt/homebrew/share/cmake/Modules/CMakeDetermineCUDACompiler.cmake:39 (_cmake_find_compiler)"
      - "CMakeLists.txt:9 (project)"
    mode: "program"
    variable: "CMAKE_CUDA_COMPILER"
    description: "CUDA compiler"
    settings:
      SearchFramework: "FIRST"
      SearchAppBundle: "FIRST"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "nvcc"
    candidate_directories:
      - "/usr/bin/"
    searched_directories:
      - "/usr/bin/nvcc"
    found: false
    search_context:
      ENV{PATH}:
        - "/Users/yadnyesh8250/.gemini/antigravity-ide/bin"
        - "/Users/yadnyesh8250/.antigravity-ide/antigravity-ide/bin"
        - "/Users/yadnyesh8250/.antigravity-ide/antigravity-ide/bin"
        - "/Users/yadnyesh8250/.antigravity/antigravity/bin"
        - "/Users/yadnyesh8250/.antigravity/antigravity/bin"
        - "/Users/yadnyesh8250/.antigravity/antigravity/bin"
        - "/Users/yadnyesh8250/.antigravity/antigravity/bin"
        - "/Users/yadnyesh8250/.antigravity/antigravity/bin"
        - "/usr/local/bin"
        - "/System/Cryptexes/App/usr/bin"
        - "/usr/bin"
        - "/bin"
        - "/usr/sbin"
        - "/sbin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin"
        - "/pkg/env/global/bin"
        - "/opt/homebrew/bin"
  -
    kind: "message-v1"
    backtrace:
      - "/opt/homebrew/share/cmake/Modules/CMakeDetermineCompilerId.cmake:1341 (message)"
      - "/opt/homebrew/share/cmake/Modules/CMakeDetermineCUDACompiler.cmake:99 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "CMakeLists.txt:9 (project)"
    message: |
      Checking whether the CUDA compiler is NVIDIA using "" did not match "nvcc: [^
      ]+ Cuda compiler driver":
  -
    kind: "message-v1"
    backtrace:
      - "/opt/homebrew/share/cmake/Modules/CMakeDetermineCompilerId.cmake:1341 (message)"
      - "/opt/homebrew/share/cmake/Modules/CMakeDetermineCUDACompiler.cmake:99 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "CMakeLists.txt:9 (project)"
    message: |
      Checking whether the CUDA compiler is Clang using "" did not match "(clang version)":
  -
    kind: "find-v1"
    backtrace:
      - "/opt/homebrew/share/cmake/Modules/Internal/CMakeCUDAFindToolkit.cmake:15 (find_program)"
      - "/opt/homebrew/share/cmake/Modules/CMakeDetermineCUDACompiler.cmake:109 (cmake_cuda_find_toolkit)"
      - "CMakeLists.txt:9 (project)"
    mode: "program"
    variable: "_CUDA_NVCC_EXECUTABLE"
    description: "Path to a program."
    settings:
      SearchFramework: "FIRST"
      SearchAppBundle: "FIRST"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "nvcc"
      - "nvcc.exe"
    found: false
    search_context:
      ENV{PATH}:
        - "/Users/yadnyesh8250/.gemini/antigravity-ide/bin"
        - "/Users/yadnyesh8250/.antigravity-ide/antigravity-ide/bin"
        - "/Users/yadnyesh8250/.antigravity-ide/antigravity-ide/bin"
        - "/Users/yadnyesh8250/.antigravity/antigravity/bin"
        - "/Users/yadnyesh8250/.antigravity/antigravity/bin"
        - "/Users/yadnyesh8250/.antigravity/antigravity/bin"
        - "/Users/yadnyesh8250/.antigravity/antigravity/bin"
        - "/Users/yadnyesh8250/.antigravity/antigravity/bin"
        - "/usr/local/bin"
        - "/System/Cryptexes/App/usr/bin"
        - "/usr/bin"
        - "/bin"
        - "/usr/sbin"
        - "/sbin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin"
        - "/pkg/env/global/bin"
        - "/opt/homebrew/bin"
...
